---
- hosts: webservers
  become: true

  tasks:  
   - name: add apt key for nodesource
     apt_key:
       url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

   - name: add repo for nodesource
     apt_repository:
        repo: 'deb https://deb.nodesource.com/node_0.10 {{ ansible_distribution_release }} main'
        update_cache: yes

   - name: install nodejs
     apt:
       name: nodejs
       state: present

   - name: Copy a single file
     ansible.builtin.copy:
      src: /home/imrankhanpgmail/demo-branch-Imran/foo.txt
      dest: /home/imrankhanpgmail/

   - name: Message from Imran
     debug:
       msg:
         - 'line added'
         - 'Line 4'                                                                                                                 29,18         Bot
